FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install

COPY . .

EXPOSE 4321

# Usar ENTRYPOINT con script de inicio
ENTRYPOINT ["bun", "run", "dev", "--host", "0.0.0.0", "--watch"] 