version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
      - /app/.astro
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    restart: unless-stopped
    init: true
